# -*- coding: utf-8 -*-
"""Bitcoin_Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1848_c-yPhwA5iTVn9iGsvii5OPYAqKTq

# Basic analysis !
"""

import pandas as pd # data pre-processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # import it for numerical computation on data
import matplotlib.pyplot as plt ## data viz libraries
import seaborn as sns

df = pd.read_csv("/content/bitcoin_price_Training - Training.csv")

df.head(3)

df.columns

df.info()

df.describe().T

"""# Data Pre-processing !"""

df.dtypes

df['Date'] = df['Date'].astype('datetime64[ns]')

df['Date'].min()

df['Date'].max()

df['Date']

type(df['Date'][0])

df.isnull().sum()

df.duplicated().sum()

df.head(3)

df.tail(5)

data = df.sort_index(ascending=False).reset_index()

"""# Analysing change in price of the stock overtime"""

data.drop('index' , axis=1 , inplace=True)

data

data.columns

plt.figure(figsize=(20,12))

for index , col in enumerate(['Open', 'High', 'Low', 'Close'] , 1):
    plt.subplot(2,2,index)
    plt.plot(df['Date'] , df[col])
    plt.title(col)

"""# Analysing open , high , low , close value of Bitcoin"""

data.shape

bitcoin_sample = data[0:50]

!pip install chart-studio
!pip install plotly

import chart_studio.plotly as py

import plotly.graph_objs as go

import plotly.express as px

from plotly.offline import download_plotlyjs , init_notebook_mode , plot , iplot

init_notebook_mode(connected=True)

trace = go.Candlestick(x=bitcoin_sample['Date'] ,
              high =bitcoin_sample['High'] ,
              open = bitcoin_sample['Open'] ,
              close = bitcoin_sample['Close'] ,
              low = bitcoin_sample['Low'])

candle_data = [trace]

layout = {
    'title':'Bitcoin Historical Price' ,
    'xaxis':{'title':'Date'}
}

fig = go.Figure(data = candle_data , layout=layout)

fig.update_layout(xaxis_rangeslider_visible = False)
fig.show()

"""# Analysing closing price (on normal scale & log-scale)"""

data['Close']

data['Close'].plot()

data.set_index('Date' , inplace=True)

data

data['Close'].plot()

np.log1p(data['Close']).plot()

plt.figure(figsize=(20,6))

plt.subplot(1,2,1)
data['Close'].plot()
plt.title('No scaling')

plt.subplot(1,2,2)
np.log1p(data['Close']).plot()
plt.title('Log scaling')
plt.yscale('log')

"""# Analyse closing Price on Yearly , Quarterly , monthly basis"""

data.head(4)

data['Close'].resample('Y').mean()

data['Close'].resample('Y').mean().plot()

data['Close'].resample('Q').mean()

data['Close'].resample('Q').mean().plot()

data['Close'].resample('M').mean()

data['Close'].resample('M').mean().plot()

"""# Analysing Daily change in Closing price of stocks"""

data['Close']

data['Close_price_pct_change'] = data['Close'].pct_change()*100

data['Close_price_pct_change']

data['Close_price_pct_change'].plot()

import chart_studio.plotly as py

import plotly.graph_objs as go

import plotly.express as px

from plotly.offline import download_plotlyjs , init_notebook_mode , plot , iplot
init_notebook_mode(connected=True)

import cufflinks as cf

cf.go_offline()

data['Close_price_pct_change']

type(data['Close_price_pct_change'])

data['Close_price_pct_change'].iplot()

